steps:
    - id: 'run helloworld'
      name: 'bash'
      entrypoint: 'sh'
      args: 
        - '-c'
        - | 
            if [ -d "environments/$BRANCH_NAME/" ]; then
              cd environments/$BRANCH_NAME
              ls
            fi
            ./helloworld.sh