steps:
    - id: 'run helloworld'
      name: 'gcr.io/cloud-builders/gcloud'
      entrypoint: 'sh'
      args: 
        - '-c'
        - | 
            pwd
            ls -ltr
            echo $BRANCH_NAME
            # chmod u+x helloworld.sh
            # sh hello-world.sh
            gsutil cp hello-world.sh gs://cloud-build-trigger-resources-bucket/ 